### ISSUE TITLE
How to optimize model fine-tuning if it is very slow? (NVIDIA GeForce RTX 4060 Laptop GPU)

### ISSUE THREAD

**Issue by mack007liu** [microsoft/windows-ai-studio#31]

**Comment by mack007liu** [comment]
11:07:20.25 0 File download from repository path microsoft/phi-2/resolve/d3186761bf5c4409f7679359284066c25ab668ee/vocab.json completed.
Information: WorkspaceAutomation.Catalog.HuggingFaceClientProvider[0]
   11:07:20.25 0 Download for model microsoft/phi-2 completed.
Debug: generate-project[0]
   11:07:20.25 0 RunProcess fileName:wsl arguments:[ --exec bash \home\mack\models\phi-2-work\phi-2\setup\first_time_setup.sh] elevated:False
Error: generate-project[0]
   11:07:20.38 0 RunProcess error:w

**Comment by mack007liu** [comment]
![image](https://github.com/microsoft/windows-ai-studio/assets/6195700/caf8aa93-a029-4b8f-8b8e-827706a4cabe)

**Comment by mack007liu** [comment]
![image](https://github.com/microsoft/windows-ai-studio/assets/6195700/63b0b196-57ab-4be0-a7a5-504bb5346231)

**Comment by mack007liu** [comment]
![超负荷001](https://github.com/microsoft/windows-ai-studio/assets/6195700/a52797e3-b8d5-4cd2-8374-c8dc6d17e442)

**Comment by mack007liu** [comment]
![超负荷002](https://github.com/microsoft/windows-ai-studio/assets/6195700/92ac1aec-546b-4155-b210-6d2147ca5110)

**Comment by ningx-ms** [comment]
Hi @mack007liu  thanks for reporting the issue. 
The slow training is mostly due to low GPU memory. Mistral-7b + QLora trained on the toy dataset consumes 17GB GPU memory. You may try a smaller model like Phi-1.5 on your laptop.

Below are training time measured a few GPUs (listed in the release notes)
![image](https://github.com/microsoft/windows-ai-studio/assets/63114126/b0d6fdc0-1d5c-4171-872e-43d16d21e2d1)
